/**
 * Danh mục Mã lỗi nghiệp vụ chuẩn toàn hệ thống
 */
export enum MaLoiNghiepVu {
  // Lỗi xác thực & phân quyền (1000 - 1999)
  XAC_THUC_THAT_BAI = 'XAC_THUC_THAT_BAI',
  KHONG_CO_QUYEN_TRUY_CAP = 'KHONG_CO_QUYEN_TRUY_CAP',
  TOKEN_HET_HAN = 'TOKEN_HET_HAN',
  TOKEN_KHONG_HOP_LE = 'TOKEN_KHONG_HOP_LE',
  TAI_KHOAN_BI_KHOA = 'TAI_KHOAN_BI_KHOA',
  EMAIL_DA_TON_TAI = 'EMAIL_DA_TON_TAI',
  MAT_KHAU_KHONG_CHINH_XAC = 'MAT_KHAU_KHONG_CHINH_XAC',

  // Lỗi dữ liệu đầu vào & Tài nguyên (2000 - 2999)
  DU_LIEU_KHONG_HOP_LE = 'DU_LIEU_KHONG_HOP_LE',
  KHONG_TIM_THAY_TAI_NGUYEN = 'KHONG_TIM_THAY_TAI_NGUYEN',
  TAI_NGUYEN_DA_TON_TAI = 'TAI_NGUYEN_DA_TON_TAI',
  YEU_CAU_KHONG_HOP_LE = 'YEU_CAU_KHONG_HOP_LE',

  // Lỗi Lớp học & Học vụ (3000 - 3999)
  LOP_HOC_DA_DONG = 'LOP_HOC_DA_DONG',
  HOC_SINH_DA_GHI_DANH = 'HOC_SINH_DA_GHI_DANH',
  BUOI_HOC_CHUA_BAT_DAU = 'BUOI_HOC_CHUA_BAT_DAU',
  BAI_TAP_HET_HAN_NOP = 'BAI_TAP_HET_HAN_NOP',

  // Lỗi Hệ thống & Bên thứ ba (5000 - 5999)
  LOI_HE_THONG = 'LOI_HE_THONG',
  LOI_DICH_VU_AI = 'LOI_DICH_VU_AI',
  LOI_PHONG_TRUC_TUYEN = 'LOI_PHONG_TRUC_TUYEN',
  LOI_LUU_TRU_TEP = 'LOI_LUU_TRU_TEP',
}
